[package]
name = "session-fs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
github-copilot-sdk.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }

[lints]
workspace = true
