[package]
name = "gcabb-desktop"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
app-model.workspace = true
copilot-provider.workspace = true
diagnostics.workspace = true
dirs.workspace = true
gpui.workspace = true
session-manager.workspace = true
storage.workspace = true
tokio.workspace = true
tracing.workspace = true
ui-components.workspace = true

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0"

[lints]
workspace = true
